### ISSUE TITLE
[Bug] Links not opening in app

### ISSUE THREAD

**Issue by TOBIBLASTER0912** [TeamVanced/Vanced#1809] opened 2023-02-05 18:51 UTC
**Bug description:**
youtube links are not opening in app instead in browser. i tried to set that youtube.com link can be opened by vanced but it does not find the link

**Does your issue exists in the vanced guides? (YES/No)**
idk

**Variant:**
nonroot

**Vanced version:**
Newest 17.03.38

**Link used to download vanced:**
Downloaded it from vanced manager

**Android version:**
Android 12 

**Device:**
Oppo Find X2 lite

**Steps to Reproduce:**
Steps to reproduce the error:
1. Click on any youtube.com/watch
2. opens in browser

**Expected behaviour:**
I expect that the video opens in the app instead of the browser

**Screen recording/screenshot of the bug:**
https://user-images.githubusercontent.com/118199012/216838900-fc51b98d-2260-46b1-a1a2-1a036d954bf2.mp4

**Comment by milindgoel15** [comment] 2023-02-09 16:49
Duplicate of #774

**Closed by milindgoel15** 2023-02-09 16:49 UTC
Labels: bug

**Comment by Viom888** [comment] 2023-02-18 08:41
I have a Simple Solution
1. Download "Android hidden Settings" app
2. Open the app and search for "default apps settings"
3. Tap "Opening links"
4. Scroll down to YouTube Vanced and tap on it
5. Tap on "Add link" and select all links below

Done 👍🏻
