### ISSUE TITLE
[Bug] connection error for no reason

### ISSUE THREAD

**Issue by DanyDany04** [TeamVanced/Vanced#1775] opened 2022-04-24 16:45 UTC
It keep give me a connection error when i'm already online. I already tried to uninstall and reinstall youtube vanced and vanced manager. The version is the last, v17.03.38

I used this link
https://youtubevanced.com/

The android version is 11 

Mi 10T Lite

Use that link, install vanced manager, install youtube vanced. In a lot of attempt even youtube music doesn't works, it just exit from the app for no reason. 

I don't know actually what happened, i just woke up and i switched on my phone and it gives me the error lol

(I have already a problem with the gallery so i can't send the video. If you want i can try to send it on discord. Dany15#2652

**Comment by milindgoel15** [comment] 2022-04-25 09:47
Duplicate of #786

**Closed by milindgoel15** 2022-04-25 09:47 UTC
Labels: bug
