### ISSUE TITLE
[Bug] connect to the internet

### ISSUE THREAD

**Issue by MhmdError** [TeamVanced/Vanced#1799] opened 2022-10-27 03:32 UTC
I keep getting this problem idk why but every time I run the app it shows and I go to sign in from another account and I came back even without adding an account and it will be solved but it's only a "temporary" solution and I need to do it every time I run the app

Lately it turns out that even the sign in button has been removed and now I can't use the app
Am from iraq btw

![Screenshot_20221027-062423](https://user-images.githubusercontent.com/116778948/198184866-d6177654-1bb8-4fd8-bbd9-4af49495f6a8.jpg)

**Comment by milindgoel15** [comment] 2022-11-04 02:48
Duplicate of #786

**Closed by milindgoel15** 2022-11-04 02:48 UTC
Labels: bug
