### ISSUE TITLE
[Error] the videos can no longer be seen and it says to update it to the most recent version so update it to the original youtube version 

### ISSUE THREAD

**Issue by Maax234** [TeamVanced/Vanced#1815] opened 2023-04-13 20:13 UTC

**Comment by BestIsReaLoL** [comment] 2023-04-13 20:18
dude ads are very annoying I'd rather not watch YouTube instead 💀💀

**Comment by pca449** [comment] 2023-04-14 00:51
> dude ads are very annoying I'd rather not watch YouTube instead 💀💀

Same here 😣

**Comment by milindgoel15** [comment] 2023-04-14 03:51
Duplicate of #1814

**Closed** 2023-04-14 03:51 UTC
Labels: bug
