### ISSUE TITLE
[Bug] YouTube will randomly refuse to open

### ISSUE THREAD

**Issue by WifiWolfREPO** [TeamVanced/Vanced#1784] opened 2022-07-18 02:19 UTC
When Vanced is installed, it runs perfectly fine.
After some time it will eventually break and refuse to work, forcing me to **uninstall it and install again** manually.
My phone is a motorola and if you want to know more please ask. 
![Screenshot_20220717-231513](https://user-images.githubusercontent.com/93295652/179436495-671056dc-3393-42e7-8b08-581d2d6ce953.png)
Thanks.
Oh, and I use the rooted way.

**Comment by milindgoel15** [comment] 2022-07-18 09:24
Duplicate of #303

**Closed** 2022-07-18 09:26 UTC
